spring:
  application:
    name: fintech

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/zb_test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      path: /h2-console
