###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "a@naver.com",
  "password": "1111",
  "userName": "홍길동",
  "phoneNumber": "1111"

}

###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
"email": "b@naver.com",
"password": "2222",
"userName": "김길수",
"phoneNumber": "2222"

}

###
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": "2",
  "initialBalance": 100
}

###
POST http://localhost:8080/transaction/amount
Content-Type: application/json

{
  "accountId": 2,
  "amount": 100
}

###
POST http://localhost:8080/transaction/amount/withdraw
Content-Type: application/json

{
  "accountId": 1,
  "amount": 100
}

###
GET http://localhost:8080/accounts/1/balance

###
POST http://localhost:8080/transfer/2
Content-Type: application/json

{
  "toAccountNumber": "08139465308686566881",
  "remittanceAmount": 100,
  "memo": "길수가 길동이한테 백원보냇다"
}